#!/bin/bash

# Remove CIRCT firtool header from text files
# Usage: ./remove_circt_header.sh /path/to/folder

FOLDER_PATH="${1:-.}"

# Check if folder exists
if [ ! -d "$FOLDER_PATH" ]; then
    echo "Error: Folder not found: $FOLDER_PATH"
    exit 1
fi

count=0

# Find all files (excluding hidden files and common binary extensions)
while IFS= read -r -d '' file; do
    # Check if file contains the target line
    if grep -q "// Generated by CIRCT firtool" "$file" 2>/dev/null; then
        # Keep only content before the target line (excluding the line itself)
        sed -i '' '/\/\/ Generated by CIRCT firtool/,$d' "$file"
        
        echo "Processed: $(basename "$file")"
        ((count++))
    fi
done < <(find "$FOLDER_PATH" -type f -not -path '*/\.*' -print0)

echo ""
echo "Done! Processed $count files."
